import {useCallback, useEffect, useMemo, useState} from "react";
import {supabase} from "../../lib/supabase";
import {formatDateForInput} from "../../shared/domain";
import type {ClientProfile} from "./types";
import {ServicePicker} from "../shared/ServicePicker";

type Service = {id: number; name: string; duration_minutes: number; price_cents: number};
type Request = {id: string; client_id: string; service_name_snapshot: string; selected_date: string; week_start?: string; week_end?: string; source: string; status: string};
type Props = {profiles: ClientProfile[]; services: Service[]; legacyEntries?: Array<{id: string; client_id: string; preferred_dates?: string[] | null; preferred_times?: string[] | null}>; onBook: (client: ClientProfile, service: string, date: string) => void};

export function SharedWaitlist({profiles, services, legacyEntries = [], onBook}: Props) {
  const [requests, setRequests] = useState<Request[]>([]);
  const [clientId, setClientId] = useState(""); const [clientQuery, setClientQuery] = useState(""); const [serviceId, setServiceId] = useState(""); const [selectedDate, setSelectedDate] = useState("");
  const [month, setMonth] = useState(() => new Date(new Date().getFullYear(), new Date().getMonth(), 1)); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const load = useCallback(async () => { const {data, error: loadError} = await supabase.rpc("admin_list_waitlist_requests", {p_include_history: true}); if (loadError) setError("Não foi possível carregar a lista compartilhada."); else setRequests((data ?? []) as Request[]); }, []);
  useEffect(() => { void load(); const channel = supabase.channel("shared-waitlist-admin").on("postgres_changes", {event: "*", schema: "public", table: "waiting_list_requests"}, () => void load()).subscribe(); return () => { void supabase.removeChannel(channel); }; }, [load]);
  const byId = useMemo(() => new Map(profiles.map((profile) => [profile.id, profile])), [profiles]);
  const matches = useMemo(() => { const query = clientQuery.trim().toLocaleLowerCase(); if (!query) return []; return profiles.filter((profile) => profile.full_name.toLocaleLowerCase().includes(query)).slice(0, 8); }, [clientQuery, profiles]);
  async function create() { if (!clientId || !serviceId || !selectedDate) { setError("Selecione cliente, serviço e data útil."); return; } setSaving(true); setError(""); const {error: saveError} = await supabase.rpc("admin_create_waitlist_request", {p_client_id: clientId, p_service_id: Number(serviceId), p_selected_date: selectedDate}); if (saveError) setError(saveError.code === "23505" ? "Esta cliente já está na lista para esse serviço nesta semana." : "Não foi possível criar a solicitação."); else { setSelectedDate(""); await load(); } setSaving(false); }
  async function cancel(id: string) { if (!window.confirm("Encerrar esta solicitação?")) return; const {error: cancelError} = await supabase.rpc("admin_cancel_waitlist_request", {p_request_id: id}); if (cancelError) setError("Não foi possível encerrar a solicitação."); else await load(); }
  const today = formatDateForInput(new Date()); const days = Array.from({length: new Date(month.getFullYear(), month.getMonth() + 1, 0).getDate()}, (_, i) => formatDateForInput(new Date(month.getFullYear(), month.getMonth(), i + 1)));
  return (<div className="admin-waiting-list"><style>{`.shared-waitlist-client-search{position:relative}.shared-waitlist-client-search input{width:100%;box-sizing:border-box;border:1px solid #d8c7cc;border-radius:11px;padding:11px 12px;background:#fff;color:#312428;font:inherit}.shared-waitlist-client-suggestions{position:absolute;z-index:20;top:calc(100% - 2px);left:0;right:0;display:grid;gap:3px;padding:6px;border:1px solid #dbc5cc;border-radius:12px;background:#fff;box-shadow:0 12px 28px rgba(86,48,62,.16)}.shared-waitlist-client-suggestions button{display:grid;gap:2px;border:0;border-radius:8px;padding:9px 10px;background:transparent;color:#5d464d;font:inherit;text-align:left;cursor:pointer}.shared-waitlist-client-suggestions button:hover{background:#f7e9ed;color:#6d3445}.shared-waitlist-client-suggestions small{color:#987a85}.shared-waitlist-selected{display:block;margin-top:6px;color:#6d3445;font-size:.8rem;font-weight:800}`}</style>
    <h3>Nova solicitação compartilhada</h3>
    <div className="admin-manual-form">
      <label className="shared-waitlist-client-search">Pesquisar cliente<input value={clientQuery} placeholder="Digite nome ou sobrenome" onChange={(event) => { setClientQuery(event.target.value); setClientId(""); }} />{matches.length > 0 && <div className="shared-waitlist-client-suggestions">{matches.map((profile) => <button type="button" key={profile.id} onClick={() => { setClientId(profile.id); setClientQuery(profile.full_name); }}>{profile.full_name}<small>{profile.phone}</small></button>)}</div>}{clientId && <span className="shared-waitlist-selected">Cliente selecionada: {byId.get(clientId)?.full_name}</span>}</label>
      <ServicePicker label="Serviço" services={services} value={serviceId} onChange={setServiceId} />
    </div>
    <div className="admin-manual-month-calendar admin-month-calendar--same-size"><div className="admin-manual-month-calendar__header"><button type="button" onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() - 1, 1))}>‹</button><strong>{month.toLocaleDateString("pt-BR", {month: "long", year: "numeric"})}</strong><button type="button" onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() + 1, 1))}>›</button></div><div className="admin-manual-month-calendar__weekdays">{["DOM", "SEG", "TER", "QUA", "QUI", "SEX", "SÁB"].map((day) => <span key={day}>{day}</span>)}</div><div className="admin-manual-month-calendar__grid">{Array.from({length: month.getDay()}, (_, i) => <span className="is-empty" key={i}/>)}{days.map((date) => { const disabled = date < today; return <button type="button" key={date} disabled={disabled} className={[selectedDate === date ? "is-selected" : "", disabled ? "is-past" : ""].filter(Boolean).join(" ")} onClick={() => setSelectedDate(date)}>{new Date(`${date}T12:00:00`).getDate()}</button>; })}</div></div>
    <button type="button" className="admin-dashboard-card" disabled={saving} onClick={() => void create()}>{saving ? "Salvando..." : "Adicionar à lista compartilhada"}</button>{error && <p className="admin-manual-form__error">{error}</p>}
    <h3>Solicitações compartilhadas</h3>
    {requests.map((request) => { const profile = byId.get(request.client_id); return <article className="admin-client-card" key={request.id}><strong>{profile?.full_name ?? "Cliente"}</strong><span>{profile?.phone ?? ""}</span><span>{request.service_name_snapshot} · {new Date(`${request.selected_date}T12:00:00`).toLocaleDateString("pt-BR")}</span><span>Semana: {request.week_start ? new Date(`${request.week_start}T12:00:00`).toLocaleDateString("pt-BR") : "—"} a {request.week_end ? new Date(`${request.week_end}T12:00:00`).toLocaleDateString("pt-BR") : "—"}</span><span>{request.source === "admin" ? "Admin" : "Cliente"} · {request.status === "active" ? "Ativa" : request.status === "cancelled" ? "Cancelada" : request.status}</span>{request.status === "active" && <div className="admin-client-card__actions"><button type="button" onClick={() => profile && onBook(profile, request.service_name_snapshot, request.selected_date)}>Agendar</button><button type="button" className="is-danger" onClick={() => void cancel(request.id)}>Encerrar</button></div>}</article>; })}
    {legacyEntries.length > 0 && <section className="shared-waitlist-legacy"><h3>Registros antigos</h3>{legacyEntries.map((entry) => { const profile = byId.get(entry.client_id); return <article key={entry.id}><strong>{profile?.full_name ?? "Cliente"}</strong><span>{profile?.phone ?? ""}</span><small>Registro anterior à nova lista · {[...(entry.preferred_dates ?? [])].join(", ") || "Preferências antigas"}</small></article>; })}</section>}
  </div>);
}
