import {useCallback, useEffect, useMemo, useState} from "react";
import {supabase} from "../../lib/supabase";
import {formatDateForInput} from "../../shared/domain";
import type {ClientProfile} from "./types";
import {ServicePicker} from "../shared/ServicePicker";
import {isClientBookingDateBlocked} from "../public/bookingDateRules";

type Service = {id: number; name: string; duration_minutes: number; price_cents: number};
type Request = {id: string; client_id: string; service_name_snapshot: string; selected_date: string; week_start?: string; week_end?: string; source: string; status: string};
type SelectedClient = {id: string; name: string; phone: string; email?: string | null};
type Props = {profiles: ClientProfile[]; services: Service[]; legacyEntries?: Array<{id: string; client_id: string; preferred_dates?: string[] | null; preferred_times?: string[] | null}>; onBook: (client: ClientProfile, service: string, date: string) => void};

export function SharedWaitlist({profiles, services, legacyEntries = [], onBook}: Props) {
  const [requests, setRequests] = useState<Request[]>([]);
  const [selectedClient, setSelectedClient] = useState<SelectedClient | null>(null);
  const [clientQuery, setClientQuery] = useState(""); const [serviceId, setServiceId] = useState(""); const [selectedDate, setSelectedDate] = useState("");
  const [month, setMonth] = useState(() => new Date(new Date().getFullYear(), new Date().getMonth(), 1)); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const load = useCallback(async () => { const {data, error: loadError} = await supabase.rpc("admin_list_waitlist_requests", {p_include_history: true}); if (loadError) setError("Não foi possível carregar a lista compartilhada."); else setRequests((data ?? []) as Request[]); }, []);
  useEffect(() => { void load(); const channel = supabase.channel("shared-waitlist-admin").on("postgres_changes", {event: "*", schema: "public", table: "waiting_list_requests"}, () => void load()).subscribe(); return () => { void supabase.removeChannel(channel); }; }, [load]);
  const byId = useMemo(() => new Map(profiles.map((profile) => [profile.id, profile])), [profiles]);
  const matches = useMemo(() => { const query = clientQuery.trim().toLocaleLowerCase(); if (!query) return []; return profiles.filter((profile) => profile.full_name.toLocaleLowerCase().includes(query)).slice(0, 8); }, [clientQuery, profiles]);
  function selectClient(profile: ClientProfile) { setSelectedClient({id: profile.id, name: profile.full_name, phone: profile.phone, email: profile.email}); setClientQuery(profile.full_name); }
  function clearSelectedClient() { setSelectedClient(null); setClientQuery(""); }
  async function create() { if (!selectedClient?.id || !serviceId || !selectedDate) { setError("Selecione cliente, serviço e data."); return; } setSaving(true); setError(""); const {error: saveError} = await supabase.rpc("admin_create_waitlist_request", {p_client_id: selectedClient.id, p_service_id: Number(serviceId), p_selected_date: selectedDate}); if (saveError) setError(saveError.code === "23505" ? "Esta cliente já está na lista para esse serviço nesta semana." : saveError.code === "22023" ? saveError.message : "Não foi possível criar a solicitação."); else { setSelectedDate(""); await load(); } setSaving(false); }
  async function cancel(id: string) { if (!window.confirm("Encerrar esta solicitação?")) return; const {error: cancelError} = await supabase.rpc("admin_cancel_waitlist_request", {p_request_id: id}); if (cancelError) setError("Não foi possível encerrar a solicitação."); else await load(); }
  const today = formatDateForInput(new Date()); const days = Array.from({length: new Date(month.getFullYear(), month.getMonth() + 1, 0).getDate()}, (_, i) => formatDateForInput(new Date(month.getFullYear(), month.getMonth(), i + 1)));
  return (<div className="admin-waiting-list"><style>{`.shared-waitlist-client-search{position:relative;display:grid;gap:6px}.shared-waitlist-client-search label{color:#6d3445;font-weight:800}.shared-waitlist-client-search input{width:100%;box-sizing:border-box;border:1px solid #d8c7cc;border-radius:11px;padding:11px 12px;background:#fff;color:#312428;font:inherit}.shared-waitlist-client-suggestions{position:absolute;z-index:30;top:calc(100% + 27px);left:0;right:0;display:grid;gap:3px;padding:6px;border:1px solid #dbc5cc;border-radius:12px;background:#fff;box-shadow:0 12px 28px rgba(86,48,62,.16);pointer-events:auto}.shared-waitlist-client-suggestions button{display:grid;gap:2px;border:0;border-radius:8px;padding:9px 10px;background:#fff;color:#5d464d;font:inherit;text-align:left;cursor:pointer;touch-action:manipulation}.shared-waitlist-client-suggestions button:hover,.shared-waitlist-client-suggestions button:focus-visible{background:#f7e9ed;color:#6d3445}.shared-waitlist-client-suggestions small{color:#987a85}.shared-waitlist-selected-card{display:grid;gap:3px;position:relative;padding:12px 76px 12px 14px;border:1px solid #d7b3a9;border-radius:12px;background:#fff8f5}.shared-waitlist-selected-card span{color:#8f4e5b;font-size:.72rem;font-weight:900;letter-spacing:.04em}.shared-waitlist-selected-card strong{color:#4d363e}.shared-waitlist-selected-card small{color:#80666e}.shared-waitlist-selected-card button{position:absolute;right:12px;top:50%;transform:translateY(-50%);border:1px solid #c98f82;border-radius:9px;padding:7px 10px;background:#fff;color:#6d3445;font:inherit;font-weight:800;cursor:pointer}.shared-waitlist-submit{display:flex;align-items:center;justify-content:center;text-align:center;width:100%;margin-top:14px;justify-self:stretch}.shared-waitlist-request-card{display:grid;gap:6px;min-width:0;margin-top:8px;padding:14px;border:1px solid #ead9df;border-radius:12px;background:#fff;color:#6d5961;overflow-wrap:anywhere}.shared-waitlist-request-card__client{display:grid;gap:3px}.shared-waitlist-request-card__client strong{color:#5f3c47;font-size:1.05rem}.shared-waitlist-request-card__client span{color:#80666e}.shared-waitlist-request-card__service,.shared-waitlist-request-card__date,.shared-waitlist-request-card__week,.shared-waitlist-request-card__status{display:block;line-height:1.4}.shared-waitlist-request-card__service{color:#5f3c47;font-weight:700}.shared-waitlist-request-card__status{color:#80666e}.shared-waitlist-request-card__actions{display:flex;gap:8px;width:100%;margin-top:6px}.shared-waitlist-request-card__actions button{flex:1;min-width:0;text-align:center}.shared-waitlist-request-card__actions .is-danger{color:#a85454}@media (max-width:430px){.shared-waitlist-request-card__actions{flex-direction:column}.shared-waitlist-request-card__actions button{width:100%}}`}</style>
    <h3>Nova solicitação compartilhada</h3>
    <div className="admin-manual-form">
      {!selectedClient ? <div className="shared-waitlist-client-search"><label htmlFor="shared-waitlist-client-input">Pesquisar cliente</label><input id="shared-waitlist-client-input" value={clientQuery} placeholder="Digite nome ou sobrenome" onChange={(event) => { setClientQuery(event.target.value); setSelectedClient(null); }} />{matches.length > 0 && <div className="shared-waitlist-client-suggestions" role="listbox">{matches.map((profile) => <button type="button" role="option" key={profile.id} onPointerDown={(event) => { event.preventDefault(); selectClient(profile); }} onClick={() => selectClient(profile)}>{profile.full_name}<small>{profile.phone}</small></button>)}</div>}</div> : <article className="shared-waitlist-selected-card"><span>CLIENTE SELECIONADA</span><strong>{selectedClient.name}</strong><small>{selectedClient.phone}</small><button type="button" onClick={clearSelectedClient}>Trocar</button></article>}
      <ServicePicker label="Serviço" services={services} value={serviceId} onChange={setServiceId} />
    </div>
    <div className="admin-manual-month-calendar admin-month-calendar--same-size"><div className="admin-manual-month-calendar__header"><button type="button" onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() - 1, 1))}>‹</button><strong>{month.toLocaleDateString("pt-BR", {month: "long", year: "numeric"})}</strong><button type="button" onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() + 1, 1))}>›</button></div><div className="admin-manual-month-calendar__weekdays">{["DOM", "SEG", "TER", "QUA", "QUI", "SEX", "SÁB"].map((day) => <span key={day}>{day}</span>)}</div><div className="admin-manual-month-calendar__grid">{Array.from({length: month.getDay()}, (_, i) => <span className="is-empty" key={i}/>)}{days.map((date) => { const isClosed = isClientBookingDateBlocked(date); const disabled = date < today || isClosed; return <button type="button" key={date} disabled={disabled} className={[selectedDate === date ? "is-selected" : "", date < today ? "is-past" : "", isClosed ? "is-blocked" : ""].filter(Boolean).join(" ")} onClick={() => setSelectedDate(date)}>{new Date(`${date}T12:00:00`).getDate()}</button>; })}</div></div>
    <button type="button" className="admin-dashboard-card shared-waitlist-submit" disabled={saving || !selectedClient?.id || !serviceId || !selectedDate} onClick={() => void create()}>{saving ? "Salvando..." : "Adicionar à lista compartilhada"}</button>{error && <p className="admin-manual-form__error">{error}</p>}
    <h3>Solicitações compartilhadas</h3>
    {requests.map((request) => { const profile = byId.get(request.client_id); return <article className="shared-waitlist-request-card" key={request.id}><div className="shared-waitlist-request-card__client"><strong>{profile?.full_name ?? "Cliente"}</strong><span>{profile?.phone ?? ""}</span></div><span className="shared-waitlist-request-card__service">Serviço: {request.service_name_snapshot}</span><span className="shared-waitlist-request-card__date">Data: {new Date(`${request.selected_date}T12:00:00`).toLocaleDateString("pt-BR")}</span><span className="shared-waitlist-request-card__week">Semana: {request.week_start ? new Date(`${request.week_start}T12:00:00`).toLocaleDateString("pt-BR") : "—"} a {request.week_end ? new Date(`${request.week_end}T12:00:00`).toLocaleDateString("pt-BR") : "—"}</span><span className="shared-waitlist-request-card__status">{request.status === "active" ? "Na lista de espera" : request.status === "cancelled" ? "Cancelada" : request.status}</span>{request.status === "active" && <div className="shared-waitlist-request-card__actions"><button type="button" onClick={() => profile && onBook(profile, request.service_name_snapshot, request.selected_date)}>Agendar</button><button type="button" className="is-danger" onClick={() => void cancel(request.id)}>Encerrar</button></div>}</article>; })}
    {legacyEntries.length > 0 && <section className="shared-waitlist-legacy"><h3>Registros antigos</h3>{legacyEntries.map((entry) => { const profile = byId.get(entry.client_id); return <article key={entry.id}><strong>{profile?.full_name ?? "Cliente"}</strong><span>{profile?.phone ?? ""}</span><small>Registro anterior à nova lista · {[...(entry.preferred_dates ?? [])].join(", ") || "Preferências antigas"}</small></article>; })}</section>}
  </div>);
}
